steps:
  - id: "List repo contents"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args: ["-lc", "echo 'PWD:' $(pwd); echo '--- TREE ---'; ls -R"]

  - id: "Install deps"
    name: python:3.11
    entrypoint: bash
    args:
      - -lc
      - |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt -t ./vendor

  - id: "Run app (impersonation -> GCS)"
    name: python:3.11
    entrypoint: bash
    env:
      - PYTHONPATH=./vendor:.
      - TARGET_SA_EMAIL=storage-access-sa@impersonation-test-489114.iam.gserviceaccount.com
      - BUCKET_NAME=awb-demo-bucket-3377
    args:
      - -lc
      - |
        python -u app/main.py

options:
  logging: CLOUD_LOGGING_ONLY
